/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "SysInit_Interface.h"
#include "SysTick_Interface.h"
#include "farmstdlib.h"

char App_MqttMessage[4];

void Frame_Cplt(void){
	/* Send image to server in Call back when frame finishes */
	Mqtt_Publish(MQTT_UART4, &Sys_MqttPhotoPubConfig);
	return;
}


int main(void)
{
	s8 Local_Temprature;
	u8 Local_Humidity;
	u8 Local_Ldr;
	u8 Local_Moisture1;
	u8 Local_Moisture2;
	u8 Local_TankState;
	u8 Local_LedGridState;

	SysInit();

	while(1){
		if(SysTick_GetTick() % 300000){
			/* Capture an image */
			OV7670_SnapShot(Frame_Cplt);
		}
		if(SysTick_GetTick() % 60000){
			/*** Take sensors readings ***/
			/* 1. Temperature */
			Aht21b_ReadTemperatureInCelsius(&Local_Temprature);
			itos(Local_Temprature, App_MqttMessage);
			Mqtt_Publish(MQTT_UART4, &Sys_MqttTempPubConfig);

			/* 2. Humidity */
			Aht21b_ReadRelativeHumidity(&Local_Humidity);
			itos(Local_Humidity, App_MqttMessage);
			Mqtt_Publish(MQTT_UART4, &Sys_MqttHumPubConfig);

			/* 3. LDR */
			Ldr_GetLuminancePercentage(&Sys_LdrConfig, &Local_Ldr);
			itos(Local_Ldr, App_MqttMessage);
			Mqtt_Publish(MQTT_UART4, &Sys_MqttLDRPubConfig);

			/* 4. Moisture */
			Fc28_GetSoilMoisturePercentage(&Sys_Fc28Config1, &Local_Moisture1);
			itos(Local_Moisture1, App_MqttMessage);
			Mqtt_Publish(MQTT_UART4, &Sys_MqttSoil1PubConfig);

			Fc28_GetSoilMoisturePercentage(&Sys_Fc28Config2, &Local_Moisture2);
			itos(Local_Moisture2, App_MqttMessage);
			Mqtt_Publish(MQTT_UART4, &Sys_MqttSoil2PubConfig);

			if(Local_Moisture1 < 10 && Local_Moisture2 < 10){
				/* Turn on valve */
				Valve_Open(&Sys_ValveWaterTankConfig);
			}

			/* 5. Tank State */
			WtrTank_GetState(&Sys_WtrTankConfig, &Local_TankState);
			itos(Local_TankState, App_MqttMessage);
			Mqtt_Publish(MQTT_UART4, &Sys_MqttTankPubConfig);

			/* 6. LED GRID STATE */
			LedGrid_GetState(&Sys_LedGridConfig, &Local_LedGridState);
			itos(Local_LedGridState, App_MqttMessage);
			Mqtt_Publish(MQTT_UART4, &Sys_MqttLightPubConfig);

		}
	}
}
